AllCops:
  Exclude:
  - 'gemfiles/**/*'

Naming/MethodName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/LineLength:
  Max: 120
