inherit_gem:
  spbtv_code_style: .strict_rubocop.yml

Style/MethodName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
