AllCops:
  Exclude:
  - 'gemfiles/**/*'

Naming/MethodName:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/NumericPredicate:
  Enabled: false

Layout/IndentHeredoc:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - Rakefile
    - fear.gemspec
    - examples/**/*

Metrics/LineLength:
  Max: 120
